language: python
python:
  - "2.7"

# instalar las dependencias
install: 
 - make install

# crear la base de datos
before_script: 
 - make createdb
 - make populate

# ejecutar tests
script: 
 - make test
