language: python
python:
  - "2.7"

# Antes de instalar, exportar la variable de entorno para trabajar con la configuración de desarrollo
before_install:
  - export DJANGO_SETTINGS_MODULE=tango_with_django_project.dev_settings

# instalar las dependencias de desarrollo
install: 
 - make install_dev

# crear la base de datos
before_script: 
 - make migrate
 - make populate

# ejecutar tests
script: 
 - make test
