---
- hosts: localhost
  vars_files:
    - vars.yml
  gather_facts: no
  become: yes

  tasks:
    - name: Instalar paquetes del sistema
      apt: pkg={{ item }} update-cache=yes cache_valid_time=3600
      with_items: "{{ system_packages }}"

    - name: Copiar el fichero de configuración de nginx
      template: src=server_config/nginx.j2 dest=/etc/nginx/sites-enabled/{{ project_name }}.conf

    - name: Copiar el fichero de configuración de gunicorn
      template: src=server_config/gunicorn.j2 dest=/etc/init/gunicorn.conf
